### ISSUE TITLE
Absolute Path

### ISSUE THREAD

**Issue by chkone** [huizhuo1987/ICCP_DL_PS#1]
Hello,

An absolute Path is visible on the Matlab code:

demo_normalEst.m (line: 43)
[Bn, canNormal, mapSet] = initialize('F:/newCode/B_matrix_updated/');

Thanks

**Comment by huizhuo1987** [comment]
Thanks, you may change it to the directory with your constructed Bmatrix

**Comment by chkone** [comment]
I know its for your git.

Thanks
